# Generated by Django 4.1.7 on 2023-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_items_risk_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='risk_index',
            field=models.FloatField(),
        ),
    ]
