# Generated by Django 4.1.7 on 2023-04-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_items_market_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='market_index_name',
            field=models.CharField(default='No data', max_length=20),
        ),
    ]
