# Generated by Django 4.1.7 on 2023-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_items_market_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='risk_change',
            field=models.FloatField(default=0.001),
        ),
    ]
