# Generated by Django 4.1.7 on 2023-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_items_risk_delta_alter_items_market_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRiskPremiumItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=7)),
                ('country_id', models.CharField(max_length=3)),
                ('country_risk_premium', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='RiskIndexItems',
        ),
    ]
