# Generated by Django 4.1.7 on 2023-03-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='risk_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
