# Generated by Django 4.1.7 on 2023-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_items_market_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='market_change',
            field=models.FloatField(default=0.001),
        ),
    ]
