# Generated by Django 4.1.7 on 2023-04-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_items_risk_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='risk_delta',
            field=models.FloatField(default=0.0001),
        ),
        migrations.AlterField(
            model_name='items',
            name='market_change',
            field=models.FloatField(default=0.0001),
        ),
        migrations.AlterField(
            model_name='items',
            name='risk_change',
            field=models.FloatField(default=0.0001),
        ),
    ]
