# Generated by Django 4.1.7 on 2023-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_countryriskpremiumitems_rename_items_riskindexitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryriskpremiumitems',
            name='date',
        ),
        migrations.AddField(
            model_name='countryriskpremiumitems',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countryriskpremiumitems',
            name='country_risk_premium',
            field=models.FloatField(default=0.0001),
        ),
    ]
